---
title: "Employee Survey Analysis"
author: "Jyueying Chen"
date: "2025-09-19"
output: html_document
---

```{r}
EmployeeSurveyData <- read.csv("EmployeeSurveyData.csv")
str(EmployeeSurveyData)
```



# Task 1: Summary Statistics and Boxplots

**Summary Statistics and Boxplot for Numerical Variables**

```{r}
str(EmployeeSurveyData)
```
```{r}
summary(EmployeeSurveyData)
```
```{r}
summary(EmployeeSurveyData$Age)
```
```{r}
summary(EmployeeSurveyData$YearofWork)
```
```{r}
boxplot(EmployeeSurveyData$Age, main="Age")
```
```{r}
boxplot(EmployeeSurveyData$YearofWork, main="YearofWork")
```


# Task 2: Factor Conversions

**Converting numerical variables to factors**


```{r}
EmployeeSurveyData$Gender <- as.factor(EmployeeSurveyData$Gender)
```
```{r}
str(EmployeeSurveyData$Gender)
```
```{r}
EmployeeSurveyData$JobSatisfaction <- as.factor(EmployeeSurveyData$JobSatisfaction)
```
```{r}
str(EmployeeSurveyData$JobSatisfaction)
```
```{r}
EmployeeSurveyData$JobCharacteristic <- as.factor(EmployeeSurveyData$JobCharacteristic)
```
```{r}
str(EmployeeSurveyData$JobCharacteristic)
```
```{r}
EmployeeSurveyData$PromotionChance <- as.factor(EmployeeSurveyData$PromotionChance)
```
```{r}
str(EmployeeSurveyData$PromotionChance)
```
```{r}
EmployeeSurveyData$AllowMakingDecision <- as.factor(EmployeeSurveyData$AllowMakingDecision)
```
```{r}
str(EmployeeSurveyData$AllowMakingDecision)
```
```{r}
EmployeeSurveyData$BudgetaryDecisionsParticipation <- as.factor(EmployeeSurveyData$BudgetaryDecisionsParticipation)
```
```{r}
str(EmployeeSurveyData$BudgetaryDecisionsParticipation)
```
```{r}
EmployeeSurveyData$LevelofProud <- as.factor(EmployeeSurveyData$LevelofProud)
```
```{r}
str(EmployeeSurveyData$LevelofProud)
```
```{r}
EmployeeSurveyData$TurnDownOtherJob <- as.factor(EmployeeSurveyData$TurnDownOtherJob)
```
```{r}
str(EmployeeSurveyData$TurnDownOtherJob)
```
```{r}
EmployeeSurveyData$RelationsBetweenEmployees <- as.factor(EmployeeSurveyData$RelationsBetweenEmployees)
```
```{r}
str(EmployeeSurveyData$RelationsBetweenEmployees)
```

# Task 3: Visualizations

**Plot the right visual for each column**

```{r}
boxplot(EmployeeSurveyData$Age, main="Age")
```
```{r}
hist(EmployeeSurveyData$YearofWork, main="YearofWork")
```
```{r}
pie(table(EmployeeSurveyData$Gender), main="Gender Distribution")
```
```{r}
barplot(table(EmployeeSurveyData$JobCharacteristic), main="JobCharacteristic")
```
```{r}
barplot(table(EmployeeSurveyData$BudgetaryDecisionsParticipation), main="BudgetaryDecisionsParticipation")
```
```{r}
barplot(table(EmployeeSurveyData$JobSatisfaction), main="JobSatisfaction")
```
```{r}
barplot(table(EmployeeSurveyData$PromotionChance), main="PromotionChance")
```
```{r}
barplot(table(EmployeeSurveyData$LevelofProud), main="LevelofProud")
```
```{r}
barplot(table(EmployeeSurveyData$RelationsBetweenEmployees), main="RelationsBetweenEmployees")
```
```{r}
barplot(table(EmployeeSurveyData$TurnDownOtherJob), main="TurnDownOtherJob")
```
# Task 4: Scatter Plots

**Plot scatter plots to show few relationships**

```{r}
scatter.smooth(EmployeeSurveyData$Age, EmployeeSurveyData$YearofWork)
```
```{r}
scatter.smooth(EmployeeSurveyData$YearofWork, EmployeeSurveyData$PromotionChance)
```
```{r}
scatter.smooth(EmployeeSurveyData$YearofWork, EmployeeSurveyData$TurnDownOtherJob)
```


```{r}
scatter.smooth(EmployeeSurveyData$JobSatisfaction, EmployeeSurveyData$LevelofProud)
```




